- framework/master-key-interface.md
- framework/master-key-provider-interface.md
add master key and master key provider interface specs
> add master key and master key provider interface specs

- framework/caching-cmm.md
chore: Small type cachimg to caching
> Fixed small typo

- .gitignore
Basic gitignore to avoid IDEs cluttering up the place.
> chore: add basic gitignore

- client-apis/decrypt.md
- client-apis/streaming.md
> chore: fix decrypt and streaming changelog

- client-apis/decrypt.md
> chore: Decrypt wording

- client-apis/encrypt.md
_Issue #, if available:_ Add missing detail for how encrypt should generate Message ID
> Specify conditions to generate message ID on Encrypt

- framework/structures.md
_Issue #, if available:_ N/A
_Description of changes:_ Fix some missing punctuation
> chore: fix missing punctuation in Structures spec

- framework/kms-keyring.md
_Issue #, if available:_ N/A
_Description of changes:_ Fix a couple typos, and change a "MAY define" to "MUST optionally define".
> docs: fix nitpicks in KMS Keyring spec

- client-apis/decrypt.md
- client-apis/encrypt.md
- data-format/message-body-aad.md
- data-format/message-body.md
- data-format/message-footer.md
- data-format/message-header.md
Fixing wording in multiple client-apis and data-format documents
> chore: Fix wording for client-apis, data-format documents

- framework/default-cmm.md
_Issue #, if available:_ Add specification for Default CMM initialization
> chore: Specify Default CMM Initialization

- framework/algorithm-suites.md
- framework/caching-cmm.md
- framework/cmm-interface.md
- framework/cryptographic-materials-cache.md
- framework/keyring-interface.md
- framework/kms-keyring.md
- framework/master-key-interface.md
- framework/master-key-provider-interface.md
- framework/multi-keyring.md
- framework/raw-aes-keyring.md
- framework/raw-rsa-keyring.md
- framework/structures.md
Wording changes for documents under the framework directory.
> chore: Wording fixes for framework documents

- framework/caching-cmm.md
> chore: update Default CMM link

- README.md
_Issue #, if available:_none
_Description of changes:_fix(Dependencies): add dependency reuirement markupsafe==2.0.1
> fix(Dependencies): add dependency requirement markupsafe==2.0.1

- framework/cryptographic-materials-cache.md
> chore: update CMC for multi-threading

- .github/workflows/ci_static-analysis.yaml
- changes/2023_7_12_update-keystore-structure/background.md
- changes/2023_7_12_update-keystore-structure/proposal.md
- framework/aws-kms/aws-kms-hierarchical-keyring.md
- framework/branch-key-store.md
- framework/structures.md
Update the structure of the DDB table
and add optional id and encryption context
to the createKey input.
> feat: Update keystore structure

- .github/workflows/ci_static-analysis.yaml
- changes/2023-06-19_thread_safe_cache/background.md
- changes/2023-06-19_thread_safe_cache/change.md
- framework/cryptographic-materials-cache.md
- framework/storm-tracking-cryptographic-materials-cache.md
- framework/synchronized-local-cryptographic-materials-cache.md
> feat: changes for thread safety

- framework/algorithm-suites.md
_Description of changes:_  add S3EC AlgorithmSuite implementation, fix a typo
> chore: add S3EC AlgorithmSuite implementation, fix a typo

- framework/branch-key-store.md
The equality statement was incomplete and therefore illogical.
> fix(BranchKeyStore): correct Custom EC equality requirement

- framework/branch-key-store.md
- Some typos
- Detail that we have implemented this
> fix(Keystore): Declare 0.3.0 released

- framework/aws-kms/aws-kms-rsa-keyring.md
> chore(KMS-RSA): Fix typos in Security Considerations

- .markdownlint.json
- changes/2024-04-08-keystore-discovery/change.md
- changes/2024-05-20-keystore-kms-config/change.md
- framework/branch-key-store.md
This PR is logically equivalent #270  .
However, @seebees and @texastony have agreed to merge this PR 
and leave #270 open so we can resolve the open issues in it
at a later date.
Thus, this PR will be merged to master when
https://github.com/aws/aws-cryptographic-material-providers-library/pull/316
is merged to mainline.
> feat(Keystore): Introduce additional KMSConfiguration options

- framework/branch-key-store.md
> chore: explicitly call out that the stored ARN does not change on VersionKey

- changes/2024-03-12_ecdh-keyring/background.md
- changes/2024-03-12_ecdh-keyring/change.md
- framework/aws-kms/aws-kms-ecdh-keyring.md
- framework/key-agreement-schemas.md
- framework/raw-ecdh-keyring.md
> feat(framework): add support for ECDH Keyring (#88)

- client-apis/encrypt.md
- framework/algorithm-suites.md
While answering a customer question about how the ESDK uses KDFs,
I struggled to find the HKDF inputs.
I think I know our spec pretty well; if I cannot find it, it maybe hard for others to find it.
To address this, 
I have added more links to the where we detail the HKDF inputs.
> chore: raise HKDF visibility

- framework/algorithm-suites.md
> chore: DDBEC should be DBE in enums

- framework/aws-kms/aws-kms-hierarchical-keyring.md
Improved description of derivedBranchKey collision probability in Security Considerations.
> refactor(H-Keyring): derivedBranchKey collision probability

- tenets.md
for supporting features such as custom CMMs, keyrings, etc.
> chore: Update tenets.md to include extensibility

- framework/branch-key-store.md
- framework/structures.md
> chore: fix typos
