awslabs/aws-encryption-sdk-specification

data-format/message-body.md

*Issue #, if available:* #51 
- Clarify final frame requirements "MUST contain exactly one" and "MUST be last frame"
- Pull "content length = plaintext length" exclusively into second bullet
- Add clarification example for "content length = plaintext length" case.

Resolve final frame content length inconsistency

---

framework/raw-rsa-keyring.md

*Issue #, if available:*
Key name and name were swapped in OnDecrypt.

Correct key name and key namespace reference in OnDecrypt

---

client-apis/encrypt.md
data-format/message-body-aad.md
data-format/message-body.md

*Issue #, if available:* closes #38 
*Description of changes:* Updates ContentLength to specify correct behavior in case framed data is being used.

Clarify Message Body AAD Content Length field for framed data

---

framework/kms-keyring.md

This line is in the Key IDs section.

fix: Key IDs MUST have kms:Encrypt

---

framework/kms-keyring.md

*Issue #, if available:* #49 
*Description of changes:* Changes to OnEncrypt/OnDecrypt to relax the dependence on generator ARN for AWS region.
*What this PR does NOT cover:* This PR does NOT redefine the Client Supplier to take a CMK ARN as input.

Remove lines mandating region be specified by KMS keyring generator

---

framework/kms-keyring.md

*Issue #, if available:*
resolves: #73 
This resolves the discrepancies found between the intent of KMS keyring behavior and configuration and the spec and adds a description of that intent.

docs: Address KMS keyring on-encrypt issues

---

framework/cmm-interface.md

*Issue #, if available:* N/A
*Description of changes:* We currently don't enforce this condition in any of our implementations, and I don't think it makes sense to add this requirement on the request, given that this sort of requirement isn't something most languages can even enforce. Additionally, restricting input in the CMM's requests isn't in line with our general philosophy that CMMs should be flexible.

Remove unneeded cmm interface precondition

---

framework/keyring-interface.md
framework/kms-keyring.md
framework/multi-keyring.md
framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md

Python and Java now have keyring implementations. This change adds links to the implementations in the keyring interface and keyring implementation specs.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Adding Python and Java implementation links to keyring specs

---

.github/not-grep.toml
.github/workflows/ci_static-analysis.yaml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
VERSIONING.md
client-apis/decrypt.md
client-apis/encrypt.md
data-format/message-body-aad.md
data-format/message-body.md
data-format/message-footer.md
data-format/message-header.md
data-format/message.md
framework/algorithm-suites.md
framework/caching-cmm.md
framework/cmm-interface.md
framework/cryptographic-materials-cache.md
framework/default-cmm.md
framework/keyring-interface.md
framework/kms-keyring.md
framework/master-key-interface.md
framework/master-key-provider-interface.md
framework/multi-keyring.md
framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md
framework/structures.md

Workflow run on this commit on my fork: https://github.com/mattsb42-aws/aws-encryption-sdk-specification/actions/runs/110828472

chore: normalize copyright headers and add workflow to require that they are set

---

framework/keyring-interface.md
framework/kms-keyring.md
framework/structures.md

* https://github.com/awslabs/aws-encryption-sdk-specification/issues/67
* Clarify naming of KMS to AWS KMS
_Follow Ups:_
* Move kms-keyring file to aws-kms-keyring

docs: Clarify naming of KMS to AWS KMS

---

framework/kms-keyring.md

* https://github.com/awslabs/aws-encryption-sdk-specification/issues/68
* https://github.com/awslabs/aws-encryption-sdk-specification/issues/55
* Rename Key IDs to Key Names for increased clarity
* Update Key Names and Generator sections to reinforce support for all AWS KMS key identifiers

docs: Update Key IDs and generator sections to reference valid AWS KMS values, additional naming clarity

---

VERSIONING.md

resolves: #104 
This refines our versioning policy and explains how it applies to specification documents and implementations.
**NOTE: This includes a change to fully adopt Semantic Versioning. This changes the requirements for MINOR versions.**

docs: define versioning policy

---

proposals/2020-06-26_decrypt-max-header-size-max-body-size/proposal.md

_Issue #, if available:_ Related to #112 
_Description of changes:_ Proposes standardizing two inputs on Decrypt to put stricter length bounds on messages to be decrypted.

feat: Add Decrypt inputs max body size and max header size

---

framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md

_Issue #, if available:_ Resolves #101 
- Clarify that Raw keyrings (raw AES keyring and raw RSA keyring) "MUST NOT" accept a key namespace value of `"aws-kms"`
- Bump the minor version of raw AES keyring and raw RSA keyring

doc(Raw Keyrings): Raw keyrings MUST NOT accept a key namespace of "aws-kms"

---

changes/2020-06-16_required-examples/change.md
examples/examples.md
examples/templates/readme.md

#103 
This initial commit only contains the requirements for examples. Either through expanding this PR or via a separate PR, I'll be adding spec documents for each of the required examples.

docs: add required examples

---

framework/multi-keyring.md

Fixes #115
Also a couple of minor grammar/readability fixes.
Note that renaming the sub-heading breaks the existing #children-keyrings anchor. I'm making the assumption that this is allowable given all current references are within this feature document. If that's not the case I can add an explicit anchor with the old symbol.

fix: Replace “children keyrings” with “child keyrings”

---

proposals/2020-07-01_aws-kms-keyring-redesign/background.md
proposals/2020-07-01_aws-kms-keyring-redesign/change.md

This proposal affects the following issues: https://github.com/awslabs/aws-encryption-sdk-specification/issues/139, https://github.com/awslabs/aws-encryption-sdk-specification/issues/94, https://github.com/awslabs/aws-encryption-sdk-specification/issues/90, https://github.com/awslabs/aws-encryption-sdk-specification/issues/84, https://github.com/awslabs/aws-encryption-sdk-specification/issues/59, https://github.com/awslabs/aws-encryption-sdk-specification/issues/16, https://github.com/awslabs/aws-encryption-sdk-specification/issues/15, https://github.com/awslabs/aws-encryption-sdk-specification/issues/49, https://github.com/awslabs/aws-encryption-sdk-specification/issues/83, https://github.com/awslabs/aws-encryption-sdk-specification/issues/40
_Description of …

feat: Proposal for re-designing the AWS KMS keyring

---

changes/2020-06-09_wrapping-key-identifiers/change.md
framework/keyring-interface.md
framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md
framework/structures.md

resolves: #21 
resolves: #47 
This change introduces definitions of the terms "key namespace", "key name", "provider ID", and "provider info", as well as  how they relate to each other.
**NOTE: I have not yet altered the keyring spec doc. That needs to happen before this merges.**

docs: add change doc to describe key namespaces, names, provider IDs, and provider info

---

changes/2020-07-13_detect-base64-encoded-messages/change.md
client-apis/decrypt.md

feat: Add recommendation for detecting base64-encoded messages

---

examples/examples.md
examples/templates/configuration/raw-keyrings/raw-aes-keyring.md

#143 
Add AES example and example template rules.
I don't *think* that adding the example template rules necessitate a change doc as I believe that they are covered under the intend of the examples change doc. I found them necessary to add in order to frame a template, and including a template in the change with them was useful both for me to clarify them for myself and to demonstrate how each section works.

docs: add AES example and rules for example templates

---

changes/2020-07-15_clarify-caching-cmm-init-params/change.md
framework/caching-cmm.md

_Issue #, if available:_ #79 
> Upon initialization, the caching Cryptographic Materials Manager (caching CMM) MUST define an underlying CMM, an underlying Cryptographic Materials Cache (CMC), and a time-to-live (TTL) for cache entries. This change clarifies that the caller MUST provide these parameters.

docs: clarify caching CMM initialization parameters

---

changes/2020-07-20_put-cache-entry-returns-nothing/change.md
framework/cryptographic-materials-cache.md

_Issue #, if available:_ #2 
> The Cryptographic Materials Cache (CMC) specification does not specify whether or not the Put Cache Entry operation returns the cache entry that it inserts. Some implementations do and others do not. This change specifies that the Put Cache Entry operation MUST NOT return the cache entry that it inserts.
Closes #2.

docs: return nothing from Put Cache Entry in CMC

---

client-apis/encrypt.md
data-format/message-body-aad.md
data-format/message-body.md
data-format/message-header.md
framework/algorithm-suites.md
framework/caching-cmm.md
framework/kms-keyring.md
framework/multi-keyring.md
framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md

moved into issues:
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/196
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/197
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/198
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/199
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/200
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/201
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/202
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/203
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/204
- https://github.com/awslabs/aws-encryption-sdk-specification/issues/205
- …

Remove TODOs to put into github issues

---

framework/algorithm-suites.md

`00 00` should be reserved for extension or other uses.

chore: Reserve algorithm suite id

---

changes/2020-06-04_how-to-fail-with-keyrings/change.md
framework/keyring-interface.md
framework/multi-keyring.md
framework/raw-aes-keyring.md
framework/raw-rsa-keyring.md

These are changes I missed making when defining decryption contracts and keyring failure modes. Now that no-ops are not allowed, if a keyring would have previously been a no-op, it MUST now fail.

fix: apply consistent behavior for refusing to write or fullfil any decryption contract

---

util/test_conditions

If the linter moves the test `DisplayName`
to a new line because of the line length,
the condition should not break.

fix: Java linter interaction with test_conditions

---

client-apis/encrypt.md

The current link is pointing to a location that doesn't exist (resulting in a 404). The commit fixes the link to a known location for the algorithm suites.

Adjust link to point to `algorithm-suites` instead of `algorithm-suite`

---

README.md

_Description of changes:_ Replaces the link to the private Duvet repo with a link to the tracking issue for making Duvet public.

docs: link to private-Duvet issue in README

---

.github/PULL_REQUEST_TEMPLATE.md

_Description of changes:_ Adds a "files moved?" checkbox to the PR template, as we have in our other repos (e.g. [aws-encryption-sdk-java](https://github.com/aws/aws-encryption-sdk-java/blob/master/.github/PULL_REQUEST_TEMPLATE.md)).

chore: add files-moved check to PR template

---

changes/2022-11-14_encryption_context_on_decrypt/background.md
changes/2022-11-14_encryption_context_on_decrypt/encryption_context_use_cases.md
framework/required-encryption-context-cmm.md

Clarify wording in `changes` in order to not imply that we are asserting that data that is sent along as AAD is protected. The importance to focus on is that customers may have data that is not sensitive, and is ok to process as AAD, but they would still prefer to not have that data stored alongside the message in readily available plaintext.
Also fix the naming in the Required Encryption Context CMM.

fix: Minor fixes to Required Encryption Context CMM

---

framework/branch-key-store.md

Avoid mixing "logical table name" and "logical keystore name" to clarify description of the Logical KeyStore Name.

docs: Clarify Logical KeyStore Name description

---

framework/keyring-interface.md

Minimal updates to the `keyring-interface` specification to reflect that there are now multiple AWS KMS keyrings.  

chore: update keyring interface to reflect KMS keyring changes

---

framework/branch-key-store.md

chore: update for mrk support in keystore

---

changes/2024-6-17_key-store-persistance/background.md
changes/2024-6-17_key-store-persistance/proposed.smithy
framework/branch-key-store.md
framework/key-store/default-encrypted-key-store.md
framework/key-store/dynamodb-encrypted-key-store.md
framework/key-store/encrypted-key-store.md

The key store defaults to DDB.
But customers have asked for
other storage options.

feat: Key store storage option

---

framework/key-store/key-storage.md
framework/structures.md

The encyrption context on hierarchical materials
is all the encryption context,
not only any custom values set by the customer
on branch key creation.

fix: Names and clarification

---

framework/aws-kms/aws-kms-hierarchical-keyring.md

A branch key version is a v4 UUID.
As such it can be converted to 16 bytes.
Also, the Encrypted Key is variable.
It is whatever length the encryption key
is for the given algorithm suite.

fix: Clarify things in the Hierarical Keyrings

---

changes/2025-01-16_key-store-mitigate-update-race/background.md
framework/branch-key-store.md
framework/key-store/dynamodb-key-storage.md
framework/key-store/key-storage.md
framework/structures.md

feat(KeyStore): Mitigate Update Race in Branch Key Store

---

framework/structures.md

0 and `null` are both OK.
This is how the Java type conversion
works for the MPL Dafny.
See: https://github.com/aws/aws-cryptographic-material-providers-library/pull/1328

fix: Update symmetric signing keys

---

framework/storm-tracking-cryptographic-materials-cache.md

chore: clarify and update the storm tracking cache

---

framework/branch-key-store.md
framework/structures.md

This PR is getting merged to `rishav/hv-2-spec`. This PR addresses comments in [PR 300](https://github.com/awslabs/aws-encryption-sdk-specification/pull/300) that is related to encryption context only. 
Note: If `encryption-context` is mentioned in the spec then do look into the input of the operation as the operation input will be specifying `encryption-context` which will clear up the context of `encryption-context`.

chore: encryption-context changes
